### ISSUE TITLE
HTTPS for logs.glob.uno

### ISSUE THREAD

**Issue by annevk** [globau/logbot#40]
Not sure if this is the right place to track this, but it would be nice to have HTTPS and even HSTS preload for the logs.

**Comment by annevk** [comment]
Oh, the logs moved and have HTTPS, my bad.

**Comment by globau** [comment]
for the record you found the right place to report issues with logbot.

as you've discovered i added HTTPS and HSTS preloading when i rewrote logbot and deployed it onto logbot.info just over a month ago (oct 18th).
