### ISSUE TITLE
Add logs for #telemetry

### ISSUE THREAD

**Issue by mcomella** [globau/logbot#43]
#telemetry is the official channel for telemetry discussions - it'd be great if there were logs. Note that I'm just a consumer of telemetry and not an owner so it may be pertinent to check with that team first if that's something they'd want (e.g. it'd be undesirable for someone to accidentally drop private data in channels and have it stored forever in logs).

**Comment by globau** [comment]
yup – my policy has always been to require sign-off from a channel op before setting up public logs.

as logbot now supports invites, the easiest way for this to happen is for a channel op to `invite` logbot to the channel.
