### ISSUE TITLE
logbot rendering is too small on some mobile devices/browsers

### ISSUE THREAD

**Issue by joeyg** [globau/logbot#48]
Not sure if this has been explored in the past. It would be great if the logbot UI was responsive for mobile usage.

**Comment by globau** [comment]
logbot is already responsive for small screens (eg. sidebar changes to auto-closing, and the nicks column changes to inline text).

**Comment by joeyg** [comment]
![GitHawk Upload by joeyg](https://i.imgur.com/1QGU4uv.jpg) @globau this is on iPhone7

**Comment by globau** [comment]
ah - thanks for the screenshot.

looks like the viewport initial-scale is wrong; i'll add a meta element.  i was able to reproduce this with one of the browsers i have on my android device.

it's weird that your browser is rendering the message text in a different size than the rest of the ui – the time, nick, and text all have the same font-size of "browser default".  i wasn't able to reproduce this issue, but i'll add an explicit `font-size:medium` to the css in the hope that helps.

**Comment by joeyg** [comment]
Thanks @globau ! Looks great!
