### ISSUE TITLE
when unable to join a channel logbot should report the reason to the requestor

### ISSUE THREAD

**Issue by imbstack** [globau/logbot#51]
Both the channel owner and an op have tried to `/invite logbot` but it doesn't seem to join. Is there maybe some sort of channel mode that we have set that we should change? It seems to have the same modes as another channel I see logbot in. Thanks for any help!

**Comment by globau** [comment]
```
[2018-02-16 18:29:34] << :bstack!sid877@moz-qafra2.0j4i.jtu0.0101.2620.IP INVITE logbot :#taskcluster-bots
[2018-02-16 18:29:34] >> JOIN #taskcluster-bots
[2018-02-16 18:29:34] << :belew.mozilla.org 405 logbot #taskcluster-bots :You are on too many channels
```

earlier this week i filed a bug asking moco ops to increase the channel limits for logbot, looks like i'll need to reopen that bug.

**Comment by globau** [comment]
reopened https://bugzilla.mozilla.org/show_bug.cgi?id=1436907

**Comment by globau** [comment]
morphing this issue to track reporting a join failure reason to the requester; i'll track the channel limit issue in bugzilla..

i should also log 405 errors to `log/irc-$network.log`

**Comment by globau** [comment]
note to self: need to catch all join-failure codes to ensure `pending_invites` is cleaned up.

**Comment by globau** [comment]
ERR_NEEDMOREPARAMS (461)
ERR_NOSUCHCHANNEL (403)
ERR_TOOMANYCHANNELS (405)
ERR_BADCHANNELKEY (475)
ERR_BANNEDFROMCHAN (474)
ERR_CHANNELISFULL (471)
ERR_INVITEONLYCHAN (473)
