### ISSUE TITLE
rate limit invites from non-op users

### ISSUE THREAD

**Issue by globau** [globau/logbot#66]
freenode is "why we can't have nice things".

the bot has been used to spam channels; if a user invites the bot to a channel, it will join the channel to get the list of users, and immediately leave if the invite was from a non-op user.
 
someone on freenode abused this feature to spam the channel with join/part messages from globbot; in the order of 30 joins within a few minutes (and over 400 invites for a single channel within a 24 hours period).

i need to add an option making the invite process manual: inviting the bot to a channel should direct the user to instead file an issue here requesting logging (with a blurb that only request from channel ops will be honoured).  i'll have to manually verify that the request is legit.

**Comment by bigpresh** [comment]
If you wanted to stay self-serve but avoid it being used for spamming, you could instead just reject requests if that user has already sent one that had to be ignored for being a non-op in the last $time_period, or if an invite had to be ignored for that channel in the last $time_period - that would seriously limit the abusability of that feature, whilst still leaving it there for legit users?

**Comment by globau** [comment]
excellent idea, thanks @bigpresh.  while it'll need a bit more plumbing it will result in a better experience for all.

**Comment by globau** [comment]
deployed.  there's a 3 minute cooldown for /invite requests from non-ops.
