### ISSUE TITLE
Additional bots

### ISSUE THREAD

**Issue by hotsphink** [globau/logbot#71]
I noticed you have a list of bots. Can you add 'mrgiggles-dev', 'confession', and 'confession-dev' to the list? (They're all the same bot. The -dev suffixes are for when I run a test instance. 'confession' is a shortcut to mrgiggles's 'note' command, to remove the need to specify a command. It's a second connection made by the same process that runs mrgiggles.)

Note that I don't usually have the -dev bots on any of the channels you're logging.

**Comment by globau** [comment]
done.
