### ISSUE TITLE
ignoring invite to already-in

### ISSUE THREAD

**Issue by alxsenen** [globau/logbot#73]
bot do not join when it was invited, regards

**Comment by globau** [comment]
which network and channel?

**Comment by alxsenen** [comment]
is a private network, in my university

**Comment by globau** [comment]
ah - then this is something you'll have to diagnose yourself.

first make sure you're running the latest version, there were some bugs which i fixed that would have caused this.

look at the output generated by logbot-irc for all references to the channel in question to ensure there's a PART event sent to the bot when it leaves the channel.  if the PART is missing (bad irc server!) logbot should detect an inconsistency during its hourly "reconciliation" checks.  this too should be clear from the logs.

**Comment by alxsenen** [comment]
this is the log in upr_irc.log
[Fri Jan  4 22:32:12 2019] [info] joining #ayuda #trivia
[Fri Jan  4 23:32:13 2019] [info] parting #ayuda #trivia
[Sat Jan  5 00:32:13 2019] [info] unexpectedly no longer in #ayuda
[Sat Jan  5 00:32:13 2019] [info] unexpectedly no longer in #trivia

 and this is my upr.yaml conf
blocked:
  - '#never_log'
  - baduser
bots:
  - bugbot
  - pulsebot
channels:
  '#lobby': {}
help: "I am zysop's logbot"
irc:
  host: 192.168.244.174:6667
  nick: zysop
  password:
  real_name: 'Syzop Logs Consumer'
name: upr
path: '~/store/upr'
timing:
  channel_reload_interval: '3600'
  initial_ping_delay: '180'
  invite_cooldown: '180'
  max_reconnect_interval: '180'
  ping_interval: '60'
  ping_timeout: '30'
  ping_timeout_attempts: '5'
  topic_reload_interval: '86400'
title: UPR
url: https://mozilla.example.com/

and i think something update my config file

**Comment by globau** [comment]
you need to look at logbot-irc's output, not the log file.
if you're using systemd that means using journalctl.
