### ISSUE TITLE
Blacklist indico-bot

### ISSUE THREAD

**Issue by pferreir** [globau/logbot#77]
Thanks for this cool service!
Can you please blacklist `indico-bot[m]` on `#indico` (Freenode)?

**Comment by globau** [comment]
not sure what you mean exactly by 'blacklist' - logbot doesn't have the ability to exclude users from its logs, nor is this a feature that i'll implement.

i've tagged `indico-bot[m]` as a bot, so you can use the "Hide IRC bots" setting should you want to hide its messages when viewing the logs.

**Comment by pferreir** [comment]
@globau yeah, that was it. Sorry for the confusion. Thanks!
