### ISSUE TITLE
sorting newest messages first / reload on changes

### ISSUE THREAD

**Issue by ghost** [globau/logbot#81]
Hi,

thank you so much for logbot, it's wonderful.

Here are two (related) things that I'm missing:

  * the ability to change the sorting of the messages.. so that the newest messages show on top.
  * have the page reload the content on change without reload (I've used https://github.com/ukhas/js-logtail in my own stuff to get that)

My use-case is that I'd like to use logbot to show incoming messages on a screen for monitoring purposes.

Regards,
Daniel

**Comment by globau** [comment]
> the ability to change the sorting of the messages.. so that the newest messages show on top

sure, that might be possible

> have the page reload the content on change without reload (I've used https://github.com/ukhas/js-logtail in my own stuff to get that)

sorry, but this isn't something that i'm keen on doing.  logbot is designed primarily for archival purposes, not as an alternative irc client.
