### ISSUE TITLE
First server disappears from UI when adding second

### ISSUE THREAD

**Issue by kiska3** [globau/logbot#83]
Behaviour:
Adding second server, makes first server unavailable eg #archiveteam on hackint the bot is still present: https://logs.kiska.pw/archiveteam however that url does not resolve, with error "The channel #archiveteam is not logged."

Expected Behaviour:
https://logs.kiska.pw/archiveteam should resolve and I should be able to see the logs for this channel

**Comment by globau** [comment]
logging of multiple networks is designed around subdomains.

so you'll need efnet.logs.kiska.pw and hackint.logs.kiska.pw resolving, as well as the correct (and different) values for `url` in each network's config file.

each subdomain needs to be configured for reverse proxying in your webserver, but you only need one instance of the mojo web server.

**Comment by kiska3** [comment]
Thank you that seems to have resolved the issue. However is there less painful way of doing this without the use of subdomains?

**Comment by kiska3** [comment]
Ok I am not sure what I have broken this time....
https://hackint.logs.kiska.pw/
https://efnet.logs.kiska.pw/
Both exist, the efnet subdomain is resolved correctly, however the hackint one is still not going to the correct network, and instead is using efnet config

Here are both configs:
hackint.yaml

> help: "I am kiska's logbot - https://logs.kiska.pw/"
> irc:
>   host: ssl:irc.hackint.org:6697
>   nick: kiskaLogBot
>   password: ~
>   real_name: 'kiska LogBot'
> name: hackint
> path: '~/store/hackint'
> timing:
>   channel_reload_interval: '3600'
>   initial_ping_delay: '180'
>   invite_cooldown: '180'
>   max_reconnect_interval: '180'
>   ping_interval: '60'
>   ping_timeout: '30'
>   ping_timeout_attempts: '5'
>   topic_reload_interval: '86400'
> title: hackint
> url: https://hackint.logs.kiska.pw/

efnet.yaml

> help: "I am kiska's logbot - https://logs.kiska.pw/"
> irc:
>   host: irc.choopa.net:6669
>   nick: kiskaLog
>   password: ~
>   real_name: 'kiska log bot'
> name: efnet
> path: '~/store/efnet'
> timing:
>   channel_reload_interval: '3600'
>   initial_ping_delay: '180'
>   invite_cooldown: '180'
>   max_reconnect_interval: '180'
>   ping_interval: '60'
>   ping_timeout: '30'
>   ping_timeout_attempts: '5'
>   topic_reload_interval: '86400'
> title: efnet
> url: https://efnet.logs.kiska.pw/

nginx sites-available

>        root /home/logbot/logbot/web/public;
> 
>         # Add index.php to the list if you are using PHP
>         index index.html index.htm index.nginx-debian.html;
> 
>         server_name logs.kiska.pw efnet.logs.kiska.pw hackint.logs.kiska.pw;
> 
>         location / {
>                 # First attempt to serve request as file, then
>                 # as directory, then fall back to displaying a 404.
>                 #try_files $uri $uri/ =404;
>                 proxy_pass http://localhost:3000/;
>             proxy_buffering off;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-Host $host:$server_port;
>         proxy_set_header X-Forwarded-Server $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
> 

Unless I am missing something, I am unsure why it would failing to do what i would like it to do

**Comment by globau** [comment]
looks like you figured it out.

except for https://logs.kiska.pw which should have a different nginx config that redirects to your default network's subdomain.
