### ISSUE TITLE
Server request: Libera.chat

### ISSUE THREAD

**Issue by kiedtl** [globau/logbot#88]
As many projects are leaving Freenode for one reason or another to move to libera.chat, it'd be pretty useful to have globbot there as well.

**Comment by globau** [comment]
Rather the follow channels to various Freenode alternatives, I'll be shutting down logbot at the end of June.

I'll announce this soon.

**Comment by kiedtl** [comment]
On 21-05-20 04:38 , glob wrote:
> Rather the follow channels to various Freenode alternatives, I'll be shutting down logbot at the end of June.

Oh, that's sad :(

Will public logs remain visible/archived (or will there be an export
system)?

**Comment by globau** [comment]
At the end of June 2021, the IRC bots running logbot will be turned off; no new messages will be collected from any networks.

Once the IRC bots have stopped running I will make archives of each channel's logs available for download.

At an undetermined time thereafter I will shutdown the logbot.info website.
